dist: bionic
language: python
python:
  - "3.7"

before_install:
  - touch .env

#install:
#  - docker-compose build

#before_script:
#  - docker-compose up -d

script:
  - echo "pass"
#  - docker-compose exec server bash -c "autoflake --remove-unused-variables --remove-all-unused-imports --ignore-init-module-imports --recursive --exclude /*/migrations/* /app/ && isort --check -m 3 --tc -w 88 --skip migrations /app/ && black --check --exclude /*/migrations/* /app/"
#  - docker-compose exec server mypy /app/

notifications:
  email: false

deploy:
  provider: script
  script: bash scripts/heroku_deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^production$
