FROM python:3.7-buster

ENV APP_DIR=/app
WORKDIR $APP_DIR

RUN apt-get update && \
    apt-get install -y wait-for-it gdal-bin postgis && \
    apt-get clean

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"
RUN poetry config virtualenvs.create false

# install Python dependencies
COPY app/poetry.lock app/pyproject.toml ./
RUN poetry install
