version: '3.7'
services:

  redis:
    container_name: redis_uptime
    image: 'redis:5.0.5'
    ports:
      - "127.0.0.1:26379:6379"
    volumes:
      - redisdata_uptime:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
      cache_from:
        - voteamerica/uptime-ci-cache:latest
    image: voteamerica/uptime-ci-cache:latest
    entrypoint: wait-for-it -t 45 postgres:5432 redis:6379 --
    command: watchmedo auto-restart --directory /app/ --pattern=*.yml --recursive -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app:cached
    ports:
      - "9901:8000"
    environment:
      - SECRET_KEY=abcd
      - DJANGO_SETTINGS_MODULE=app.settings
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DD_AGENT_HOST=ddagent
      - DD_DOGSTATSD_PORT=3333
    env_file:
      - .env
      - .env-prod
    depends_on:
#      - postgres
      - redis

  beat:
    image: voteamerica/uptime-ci-cache:latest
    entrypoint: wait-for-it -t 45 postgres:5432 redis:6379 --
    command: watchmedo auto-restart --directory /app/ --pattern=*.py --recursive -- python -m celery -A app.celery_beat beat --scheduler redbeat.RedBeatScheduler
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=abcd
      - DJANGO_SETTINGS_MODULE=app.settings
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DD_AGENT_HOST=ddagent
      - DD_DOGSTATSD_PORT=3333
    env_file:
      - .env
      - .env-prod
    depends_on:
#      - postgres
      - redis

  worker:
    image: voteamerica/uptime-ci-cache:latest
    entrypoint: wait-for-it -t 45 postgres:5432 redis:6379 selenium:4444 --
    command: watchmedo auto-restart --directory /app/ --patterns='*.py;*.yml' --recursive -- python -m celery -A app.celery_app worker -Q default
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=abcd
      - DJANGO_SETTINGS_MODULE=app.settings
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DD_AGENT_HOST=ddagent
      - DD_DOGSTATSD_PORT=3333
    env_file:
      - .env
      - .env-prod
    depends_on:
#      - postgres
      - redis
      - beat
      - selenium

  selenium:
    image: selenium/standalone-chrome:3.141.59
    ports:
      - "4444:4444"
    shm_size: '2gb'

  echo:
    image: voteamerica/uptime-ci-cache:latest
    command: python -m echo
    volumes:
      - ./app/echo.py:/app/echo.py
    ports:
      - "13333:3333"

volumes:
  pgdata_uptime:
  redisdata_uptime:
