# Generated by Django 3.1.4 on 2020-12-16 21:58

import common.enums
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('state', models.TextField(choices=[(common.enums.ProxyStatus['CREATING'], 'creating'), (common.enums.ProxyStatus['PREPARING'], 'preparing'), (common.enums.ProxyStatus['UP'], 'up'), (common.enums.ProxyStatus['BURNED'], 'burned'), (common.enums.ProxyStatus['DOWN'], 'down')], null=True)),
                ('failure_count', models.IntegerField(null=True)),
                ('last_used', models.DateTimeField(null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('state_up', models.BooleanField(null=True)),
                ('state_changed_at', models.DateTimeField(null=True)),
                ('last_tweet_at', models.DateTimeField(null=True)),
                ('uptime_day', models.FloatField(null=True)),
                ('uptime_week', models.FloatField(null=True)),
                ('uptime_month', models.FloatField(null=True)),
                ('uptime_quarter', models.FloatField(null=True)),
                ('blocked', models.BooleanField(null=True)),
                ('blocked_changed_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_up', models.BooleanField(null=True)),
                ('blocked', models.BooleanField(null=True)),
                ('ignore', models.BooleanField(null=True)),
                ('load_time', models.FloatField(null=True)),
                ('error', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('proxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uptime.proxy')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uptime.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteDowntime',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('down_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_down', to='uptime.sitecheck')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uptime.site')),
                ('up_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_up', to='uptime.sitecheck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='last_went_blocked_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_blocked', to='uptime.sitecheck'),
        ),
        migrations.AddField(
            model_name='site',
            name='last_went_down_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_down', to='uptime.sitecheck'),
        ),
        migrations.AddField(
            model_name='site',
            name='last_went_unblocked_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_unblocked', to='uptime.sitecheck'),
        ),
        migrations.AddField(
            model_name='site',
            name='last_went_up_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_up', to='uptime.sitecheck'),
        ),
    ]
