# Generated by Django 3.1.4 on 2020-12-19 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_up', models.BooleanField(null=True)),
                ('blocked', models.BooleanField(null=True)),
                ('ignore', models.BooleanField(null=True)),
                ('load_time', models.FloatField(null=True)),
                ('error', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.TextField(choices=[('CREATING', 'creating'), ('PREPARING', 'preparing'), ('UP', 'up'), ('BURNED', 'burned'), ('DOWN', 'down')], null=True)),
                ('failure_count', models.IntegerField(null=True)),
                ('last_used', models.DateTimeField(null=True)),
                ('metadata', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('metadata', models.JSONField(null=True)),
                ('state_up', models.BooleanField(null=True)),
                ('state_changed_at', models.DateTimeField(null=True)),
                ('last_tweet_at', models.DateTimeField(null=True)),
                ('uptime_day', models.FloatField(null=True)),
                ('uptime_week', models.FloatField(null=True)),
                ('uptime_month', models.FloatField(null=True)),
                ('uptime_quarter', models.FloatField(null=True)),
                ('blocked', models.BooleanField(null=True)),
                ('blocked_changed_at', models.DateTimeField(null=True)),
                ('last_went_blocked_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_blocked', to='uptime.check')),
                ('last_went_down_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_down', to='uptime.check')),
                ('last_went_unblocked_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_unblocked', to='uptime.check')),
                ('last_went_up_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_up', to='uptime.check')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_down_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_first', to='uptime.check')),
                ('last_down_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_last', to='uptime.check')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uptime.site')),
                ('up_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_up', to='uptime.check')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassifierPattern',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.TextField(choices=[('BODY_REQUIRED', 'body_required'), ('TITLE_DOWN', 'title_down'), ('BODY_DOWN', 'body_down'), ('BODY_BLOCKED', 'body_blocked')])),
                ('pattern', models.TextField()),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uptime.classifier')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='check',
            name='proxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uptime.proxy'),
        ),
        migrations.AddField(
            model_name='check',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uptime.site'),
        ),
    ]
