# Generated by Django 3.1.5 on 2021-01-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='down',
        ),
        migrations.AddField(
            model_name='site',
            name='last_downtime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_last', to='uptime.downtime'),
        ),
        migrations.AddField(
            model_name='site',
            name='up',
            field=models.BooleanField(null=True),
        ),
    ]
