# Generated by Django 3.1.4 on 2020-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='state',
            field=models.TextField(choices=[('CREATING', 'creating'), ('PREPARING', 'preparing'), ('UP', 'up'), ('BURNED', 'burned'), ('DOWN', 'down')], null=True),
        ),
    ]
