# Generated by Django 3.1.13 on 2022-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='region',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.TextField(choices=[('CREATING', 'creating'), ('PREPARING', 'preparing'), ('UP', 'up'), ('BURNED', 'burned'), ('DOWN', 'down'), ('RETIRED', 'retired')], null=True),
        ),
    ]
