# Generated by Django 3.1.5 on 2021-01-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0002_auto_20210112_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='content',
        ),
        migrations.AddField(
            model_name='check',
            name='content_url',
            field=models.TextField(null=True),
        ),
    ]
