# Generated by Django 3.1.4 on 2020-12-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0003_auto_20201217_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteCheck',
            new_name='Check',
        ),
        migrations.RenameModel(
            old_name='SiteDowntime',
            new_name='Downtime',
        ),
    ]
