# Generated by Django 3.1.5 on 2021-01-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0004_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.TextField(choices=[('UP', 'up'), ('DOWN', 'down'), ('BLOCKED', 'blocked')], null=True),
        ),
    ]
