# Generated by Django 3.1.4 on 2020-12-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0005_classifier_classifierpattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='state',
            new_name='status',
        ),
    ]
