# Generated by Django 3.1.5 on 2021-01-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0005_site_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='blocked_changed_at',
            new_name='status_changed_at',
        ),
        migrations.RemoveField(
            model_name='site',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='site',
            name='last_came_up_check',
        ),
        migrations.RemoveField(
            model_name='site',
            name='state_changed_at',
        ),
        migrations.RemoveField(
            model_name='site',
            name='up',
        ),
    ]
