# Generated by Django 3.1.4 on 2020-12-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0006_auto_20201218_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
