# Generated by Django 3.1.4 on 2020-12-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0002_auto_20201217_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
